Add bit and wire equivalents
lac-dcc/chimera pull request #41
Opened 2024-09-26 12:10 UTC by luizademelo

- Addition of the bit type in the type inference
- Creation of new CanonicalTypes which represent other variations of "net_type"(TRI, TRI0, TRI1, SUPPLY0, SUPPLY1, WOR, WAND, UWIRE)

2024-09-26 17:36 UTC, luizademelo commented
### Net types description
- `wire` and `tri`: identical in their syntax functions
- `uwire`: model nets that allow only a single driver
- `wor`, `wand`: model wired logic configurations
- `tri0` and `tri1`: model nets with resistive pulldown and pullup
- `supply0` and ` supply1`: model the power supplies in a circuit

2024-10-02 11:58 UTC, joaovam requested changes

2024-10-02 11:58 UTC, joaovam commented on src/TypeInference.h
> +  UWIRE,
You can remove these types from the enum

2024-10-02 11:58 UTC, joaovam commented on src/TypeInference.cpp
> +      " supply0 ", " supply1 ", " wor ",  " wand "};
Can we add uwire to this set?

2024-10-02 13:04 UTC, joaovam approved these changes

2024-10-02 13:07 UTC, merged